### ISSUE TITLE
Transfer blockdiag organization offer

### ISSUE THREAD

**Issue by tk0miya** [blockdiag-zh/blockdiag.github.io#1]
Hello, I'm author of blockdiag.
Now, I have a plan to move the repositories to github from bitbucket.
Could you please transfer this organization to me?

Regards,

**Comment by guiquanz** [comment]
Ok!

**Comment by guiquanz** [comment]
I have renamed this organization  to blockdiag-zh and you can take the name away now.

**Comment by tk0miya** [comment]
Thank you very much!
I got the `blockdiag` organization right now.
